import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/sidebar'
// import HomeIcon from '@mui/icons-material/Home';
// import SearchIcon from '@mui/icons-material/Search';
// import FavoriteIcon from '@mui/icons-material/Favorite';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className={styles.content}>
        <div className={styles.last_tracks}>
          <div className={styles.title}>
            <h1>Good evening</h1>
            <h1>Last tracks</h1>
          </div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
        </div>
        <div className={styles.playlists}>
          <div className={styles.title}>
            <h1>Playlists for you</h1>
            
          </div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
        </div>
      </div>
      <div className={styles.player}>
        <h1> Player </h1>
      </div>
    </div>
  );
}

export default Home

