import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Sidebar from '../components/sidebar'
import Content from '../components/content'
import * as React from 'react';
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import Slider from '@mui/material/Slider';
import LibraryBooksIcon from '@mui/icons-material/LibraryBooks';
import VolumeUp from '@mui/icons-material/VolumeUp';
import PlayCircleIcon from '@mui/icons-material/PlayCircle';
import SkipPreviousIcon from '@mui/icons-material/SkipPrevious';
import SkipNextIcon from '@mui/icons-material/SkipNext';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <Content/>
      {/* <div className={styles.content}>
        <div className={styles.last_tracks}>
          <div className={styles.title}>
            <h1>Good evening</h1>
            <h1>Last tracks</h1>
          </div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
          <div className={styles.track_card}>song</div>
        </div>
        <div className={styles.playlists}>
          <div className={styles.title}>
            <h1>Playlists for you</h1>
          </div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
        </div>
      </div> */}
      <div className={styles.player}>
        <div className={styles.prewiev}></div>
        <div className={styles.play_module}>
        <div className={styles.module_btns}>
            <SkipPreviousIcon className={styles.skip_back} sx={{ fontSize: "30px" }} />
            <PlayCircleIcon className={styles.pause} sx={{ fontSize: "40px" }} />
            <SkipNextIcon className={styles.skip_next} sx={{ fontSize: "30px", justifyContent: 'start'}} />
          </div>
        </div>
        <div className={styles.functions}>
          <div className={styles.table}>
            <Stack
              spacing={2}
              direction="row"
              sx={{ mb: 1 }}
              alignItems="center"
            >
              <LibraryBooksIcon sx={{ fontSize: "30px" }} />
            </Stack>
          </div>
          <Box sx={{ width: "80%" }}>
            <Stack
              spacing={2}
              direction="row"
              sx={{ mb: 1 }}
              alignItems="center"
            >
              <VolumeUp sx={{ fontSize: "30px" }} />
              <Slider />
            </Stack>
          </Box>
        </div>
      </div>
    </div>
  );
}

export default Home

