
import Head from 'next/head'
import { useRouter } from 'next/router'
import Sidebar from '../../components/sidebar'
import Content from '../../components/content'
import Player from '../../components/Player'
import * as React from 'react';
import styles from '../../styles/Home.module.css'
import { ITrack } from '../../types/track'
import TrackList from '../../components/TrackList'

const Index = () => {
  const router = useRouter()
  const tracks: ITrack[] = [
    {_id: '1', name: 'Antidepressant', artist: 'FACE', text: 'сатань мне антидепрессантом', listens:0, picture: 'http://localhost:3333/image/4637ef5a-3853-4a49-92b2-674d78f36419.png', audio: 'http://localhost:3333/audio/ae99f18a-9b6a-4852-8154-834323dc5066.mp3'},
    {_id: '2', name: 'Antidepressant', artist: 'FACE', text: 'сатань мне антидепрессантом', listens:0, picture: 'http://localhost:3333/image/4637ef5a-3853-4a49-92b2-674d78f36419.png', audio: 'http://localhost:3333/audio/9e3fbd8c-f568-4f2d-9231-25d31076e03a.mp3'},
    {_id: '3', name: 'Antidepressant', artist: 'FACE', text: 'сатань мне антидепрессантом', listens:0, picture: 'http://localhost:3333/image/4637ef5a-3853-4a49-92b2-674d78f36419.png', audio: 'http://localhost:3333/audio/9e3fbd8c-f568-4f2d-9231-25d31076e03a.mp3'},
    {_id: '4', name: 'Antidepressant', artist: 'FACE', text: 'сатань мне антидепрессантом', listens:0, picture: 'http://localhost:3333/image/4637ef5a-3853-4a49-92b2-674d78f36419.png', audio: 'http://localhost:3333/audio/9e3fbd8c-f568-4f2d-9231-25d31076e03a.mp3'},
    {_id: '5', name: 'Antidepressant', artist: 'FACE', text: 'сатань мне антидепрессантом', listens:0, picture: 'http://localhost:3333/image/4637ef5a-3853-4a49-92b2-674d78f36419.png', audio: 'http://localhost:3333/audio/9e3fbd8c-f568-4f2d-9231-25d31076e03a.mp3'},
    {_id: '6', name: 'Antidepressant', artist: 'FACE', text: 'сатань мне антидепрессантом', listens:0, picture: 'http://localhost:3333/image/4637ef5a-3853-4a49-92b2-674d78f36419.png', audio: 'http://localhost:3333/audio/9e3fbd8c-f568-4f2d-9231-25d31076e03a.mp3'}
  ]
  return (
    <div className={styles.container}>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      {/* <Content /> */}
      <div className={styles.content}>
        {/* TrackList */}
        <TrackList tracks={tracks}/>
        <div className={styles.playlists}>
          <div className={styles.title}>
            <h1 style={{marginBottom:"30px"}}>Playlists for you</h1>
          </div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
          <div className={styles.playlist_card}></div>
        </div>
      </div>
      <Player />
    </div>
  );
}

export default Index

